web/router.ex
defmodule Mobil.Plugs.AdminRestricted do
  import Plug.Conn

  def init(default), do: default

  def call(conn, default) do
    # If the user is authenticated, use admin layout. Else redirect back to login.
    if !Plug.Conn.get_session(conn, :current_user) do
      Phoenix.Controller.redirect(conn, to: "/login")
    else
      Phoenix.Controller.put_layout(conn, {Mobil.LayoutView, "admin_app.html"})
    end
  end
end

defmodule Mobil.Router do
  use Mobil.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :restricted_browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Mobil.Plugs.AdminRestricted
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Mobil do
    pipe_through :browser

    get "/", SubscriptionController, :index
    get "/login", SessionController, :new
    post "/login", SessionController, :create
    delete "/logout", SessionController, :delete

    resources "/companies", CompanyController
    resources "/subscriptions", SubscriptionController
    resources "/articles", ArticleController
  end

  scope "/admin", Mobil.Admin, as: :admin do
    pipe_through :restricted_browser

    get "/", SubscriptionController, :index
    resources "/companies", CompanyController
    resources "/subscriptions", SubscriptionController
    resources "/articles", ArticleController
  end
end

web/views/layout_view.ex
defmodule Mobil.LayoutView do
  use Mobil.Web, :view
end

web/templates/layout/admin_app.html.eex
<!DOCTYPE html>
<html>
<head>
  <title>Mobil administration interface</title>
  <script src="//tinymce.cachefly.net/4.2/tinymce.min.js"></script>
  <script>
  tinymce.init({
    selector: '.wysiwyg',
    plugins: [
      "code"
    ],
    toolbar: "undo redo | styleselect | bold italic | link image | alignleft aligncenter alignright | charmap code"
  });
  </script>
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/admin_app.css") %>">
</head>
<body>

<div id="wrapper">
  <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
      <a class="navbar-brand" href="/admin">ADMINISTRATION</a>
    </div>

    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <ul class="nav navbar-top-links navbar-right">
      <li>
        <%= link "Logout", to: session_path(@conn, :delete) %>
      </li>
    </ul>

    <div class="navbar-default sidebar" role="navigation">
      <div class="sidebar-nav navbar-collapse">
        <ul class="nav" id="side-menu">
          <li>
            <%#= link_to '<i class="fa fa-dashboard fa-fw"></i> Dashboard'.html_safe, admin_articles_path %>
          </li>
          <li>
            <a href="#"><i class="fa fa-users"></i> Articles<span class="fa arrow"></span></a>
            <ul class="nav nav-second-level">
              <li>
                <%= link "Articles", to: admin_article_path(@conn, :index) %>
              </li>
              <li>
                <%= link "Create article", to: admin_article_path(@conn, :new) %>
              </li>
            </ul>
          </li>
          <li>
            <a href="#"><i class="fa fa-users"></i> Companies<span class="fa arrow"></span></a>
            <ul class="nav nav-second-level">
              <li>
                <%= link "Companies", to: admin_company_path(@conn, :index) %>
              </li>
              <li>
                <%= link "Create company", to: admin_company_path(@conn, :new) %>
              </li>
            </ul>
          </li>
          <li>
            <a href="#"><i class="fa fa-users"></i> Subscriptions<span class="fa arrow"></span></a>
            <ul class="nav nav-second-level">
              <li>
                <%= link "Subscriptions", to: admin_subscription_path(@conn, :index) %>
              </li>
              <li>
                <%= link "Create subscription", to: admin_subscription_path(@conn, :new) %>
              </li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div id="page-wrapper">

    <%= if get_flash(@conn, :info) do %>
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <% end %>
    <%= if get_flash(@conn, :error) do %>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
    <% end %>

    <%= @inner %>

    <div class="row invisible">
      <div class="col-lg-8">
        <div class="panel panel-default invisible">
          <div class="panel-body">
            <div id="morris-area-chart"></div>
          </div>
        </div>
        <div class="col-lg-8 .invisible">
          <div id="morris-bar-chart"></div>
        </div>
      </div>
      <div class="col-lg-4 invisible">
        <div id="morris-donut-chart"></div>
      </div>
    </div>
  </div>
</div>

<script src="<%= static_path(@conn, "/js/vendor.js") %>"></script>
<script src="<%= static_path(@conn, "/js/admin_app.js") %>"></script>
<script>require("web/static/js/admin_app").AdminApp.run()</script>

</body>
</html>

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= if @conn.assigns[:meta_description] do %>
      <meta name="description" content="<%= @conn.assigns[:meta_description] %>">
    <% else %>
      <meta name="description" content="Den bästa sidan att hitta rätt mobilabonnemang! Jämför mobilabonnemang i Sverige. Det är snabbt, enkelt och sparar dig pengar!">
    <% end %>

    <link rel="icon" type="image/png" href="/images/24x24.ico" />
    <!-- TradeDoubler site verification 2772315 -->
    <%= if Mix.env == :prod do %>
      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', 'UA-67990507-1', 'auto');
        ga('send', 'pageview');
      </script>
    <% end %>

    <title><%= if @conn.assigns[:page_title], do: "Mobil-abonnemang.se | #{@conn.assigns[:page_title]}", else: "Mobil-abonnemang.se" %></title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body class="<%= if @conn.request_path == "/", do: "frontpage" %>">
    <header class="site-header">
      <div class="site-wrapper">
        <div class="site-header__logo">
          <h1>
            <img alt="Logo simcard" src="/images/logosimcard.png">
            <%= link to: subscription_path(@conn, :index) do %>
              <span class="site-header__logo__green">Mobil</span>abonnemang.se</a>
            <% end %>
          </h1>
        </div>
        <nav>
          <ul style="float:right;">
            <li>
              <%= link "Guides", to: article_path(@conn, :index) %>
            </li>
            <li>
              <%= link "Abonnemang", to: subscription_path(@conn, :index) %>
            </li>
          </ul>
        </nav>
      </div>
    </header>
    <div class="site-wrapper">
      <div class="frontpage aside">
        <ul>
          <li>
            <%= render_existing view_module(@conn), "aside.html", assigns %>
          </li>
        </ul>
      </div>

      <div class="site-outlet">
        <%= @inner %>
      </div>

      <div class="clearfix"></div>
    </div>

    <footer class="site-footer center">
      <h1 class="site-footer__big">
        <span class="site-header__logo__green">Mobil</span>abonnemang</a>
      </h1>
      <h2 class="site-footer__medium">
        Den bästa sidan att hitta rätt mobilabonnemang!</h2>
      <h2 class="site-footer__small">
        Konsument guider, Recensioner, bekvämt och snabbt,  Spara pengar
      </h2>
    </footer>

    <script src="<%= static_path(@conn, "/js/vendor.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>require("web/static/js/app").App.run()</script>
  </body>
</html>